In [63]:
import pandas as pd
from pathlib import Path

# Dataset + Metadata Loading & Overview

In [64]:
BASE = Path("../data/raw")

# Meta data incelicez ilk önce, iç yapısını ve sütunların ne anlama geldiğini anlamak için.
meta_data_df = pd.read_csv(BASE / "all_metadata.csv")

print("Shape:", meta_data_df.shape)
print("Columns:", meta_data_df.columns.tolist())
print("Dtypes:", meta_data_df.dtypes.tolist())
print("Head:")
meta_data_df.head()

Shape: (1920, 13)
Columns: ['Variant_name', 'Run_Batch', 'Variant_path', 'date_created', 'date_loaded', 'FSW_rows', 'Simulation_columns', 'FSW_columns', 'Scenario', 'Month', 'Time_offset', 'Description', 'data_file']
Dtypes: [dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('O'), dtype('O')]
Head:

,Variant_name,Run_Batch,Variant_path,date_created,date_loaded,FSW_rows,Simulation_columns,FSW_columns,Scenario,Month,Time_offset,Description,data_file
0,1_0.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_0....,2025-08-29T03:54:34.216196,2025-08-29T03:54:45.984822,602,69,134,baseline,January,0.0,Firesat_Baseline January Time Offset:0.0,./data/raw/baseline/fsw_data_1_0.0_0.csv
1,1_36.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_36...,2025-08-29T03:54:46.089648,2025-08-29T03:54:58.827963,602,69,134,baseline,January,36.0,Firesat_Baseline January Time Offset:36.0,./data/raw/baseline/fsw_data_1_36.0_0.csv
2,1_72.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_72...,2025-08-29T03:54:58.928442,2025-08-29T03:55:11.794282,602,69,134,baseline,January,72.0,Firesat_Baseline January Time Offset:72.0,./data/raw/baseline/fsw_data_1_72.0_0.csv
3,1_108.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_10...,2025-08-29T03:55:11.900084,2025-08-29T03:55:23.651383,602,69,134,baseline,January,108.0,Firesat_Baseline January Time Offset:108.0,./data/raw/baseline/fsw_data_1_108.0_0.csv
4,1_144.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_14...,2025-08-29T03:55:23.744846,2025-08-29T03:55:35.496401,602,69,134,baseline,January,144.0,Firesat_Baseline January Time Offset:144.0,./data/raw/baseline/fsw_data_1_144.0_0.csv

In [65]:
print("Tail:")
meta_data_df.tail()

Tail:

,Variant_name,Run_Batch,Variant_path,date_created,date_loaded,FSW_rows,Simulation_columns,FSW_columns,Scenario,Month,Time_offset,Description,data_file
1915,12_324.0_-50,Firesat_Attack_RWC,Firesat_Attack_RWC/FireSat_updated_12_324.0_-5...,2025-08-29T02:49:55.770782,2025-08-29T02:50:07.523443,602,69,134,attack_rwc,December,324.0,Firesat_Attack_RWC December Time Offset:324.0,./data/raw/attack_rwc/fsw_data_12_324.0_-50.csv
1916,12_324.0_-25,Firesat_Attack_RWC,Firesat_Attack_RWC/FireSat_updated_12_324.0_-2...,2025-08-29T02:50:07.622140,2025-08-29T02:50:19.391689,602,69,134,attack_rwc,December,324.0,Firesat_Attack_RWC December Time Offset:324.0,./data/raw/attack_rwc/fsw_data_12_324.0_-25.csv
1917,12_324.0_0,Firesat_Attack_RWC,Firesat_Attack_RWC/FireSat_updated_12_324.0_0....,2025-08-29T02:50:19.488263,2025-08-29T02:50:31.228495,602,69,134,attack_rwc,December,324.0,Firesat_Attack_RWC December Time Offset:324.0,./data/raw/attack_rwc/fsw_data_12_324.0_0.csv
1918,12_324.0_25,Firesat_Attack_RWC,Firesat_Attack_RWC/FireSat_updated_12_324.0_25...,2025-08-29T02:50:31.327610,2025-08-29T02:50:43.073062,602,69,134,attack_rwc,December,324.0,Firesat_Attack_RWC December Time Offset:324.0,./data/raw/attack_rwc/fsw_data_12_324.0_25.csv
1919,12_324.0_50,Firesat_Attack_RWC,Firesat_Attack_RWC/FireSat_updated_12_324.0_50...,2025-08-29T02:50:43.180588,2025-08-29T02:50:54.919491,602,69,134,attack_rwc,December,324.0,Firesat_Attack_RWC December Time Offset:324.0,./data/raw/attack_rwc/fsw_data_12_324.0_50.csv

In [66]:
#Metadata sütunlarının dağılımlarını inceleyelim.
#Metadata'da senaryo dağılımı:

meta_data_df["Scenario"].value_counts()

Scenario
attack_rwa    600
attack_rwb    600
attack_rwc    600
baseline      120
Name: count, dtype: int64

In [67]:
# FSW Row metadata içerisindeki 1920 csv dosyasının her birinde kaç satır olduğunu yani her bir csv dosyasının kaç example içerdiğini göseriyor. 1hz sıklıkla kaydedilen yani saniyede bir kaydedilen 10 dakikalık veriler oldukları için hepsinde 60 * 10 + 2 example var. FSW row bunu gösteriyor. 
# Metadata FSW Row:
meta_data_df["FSW_rows"].value_counts()

# Görüldüğü üzere 2 csv dosyasında anormallik var, yani 2 csv dosyasında diğerlerinin aksine 602 satır yok. EDA adımında olduğumuz için müdahele yok ama bu anormalliği kafamızda not aldık.

FSW_rows
602    1918
510       1
341       1
Name: count, dtype: int64

In [68]:
# FSW Column da metadata içerisindeki 1920 csv dosyasının her birinde kaç feature olduğunu gösteriyor, 600 örneğin feature sayısını veriyor yani.
# Metadata FSW Columns:
meta_data_df["FSW_columns"].value_counts()
# Görüldüğü üzere burada da bazı csv dosyalarında column dengesizliği var, bunlara da ileride bakmak için not aldık.

FSW_columns
134    1726
127     192
90        2
Name: count, dtype: int64

In [69]:
# Metadata Month dağılımı:
meta_data_df["Month"].value_counts()
# Dengeli sorun yok.

Month
January      160
February     160
March        160
April        160
May          160
June         160
July         160
August       160
September    160
October      160
November     160
December     160
Name: count, dtype: int64

In [70]:
#Metadata Time Offset:
meta_data_df["Time_offset"].value_counts()
#Dengeli sorun yok.

# Bu incelenecek son sütun değeri idi, kalanları işimize yaramayacak şeyler, şimdi data file'lara bakalım.

Time_offset
0.0      192
36.0     192
72.0     192
108.0    192
144.0    192
180.0    192
216.0    192
252.0    192
288.0    192
324.0    192
Name: count, dtype: int64

In [71]:
# Then we have the data files themselves. We can reach them by using the paths in the metadata "data_file" column.
#örnek baseline csv dosyası içeriği:
sample_baseline_df = pd.read_csv(BASE / "baseline/fsw_data_1_72.0_0.csv")
sample_baseline_df.head()

# bu şekilde metadata üzerinden data file'lara erişebiliyoruz.

,FswTime(sec),CurrentYear(year),CurrentMonth(month),CurrentDay(day),CurrentHour(hour),CurrentMinute(min),CurrentSecond(sec),Latitude(rad),Longitude(rad),Altitude(m),...,Run_Batch,date_loaded,date_created,UTC,Longitude(deg),Latitude(deg),TimeDelay,Scenario,Run_Batch_Variant,result_label
0,59,2025,1,0,12,19,14,1.27909,-2.33570,900032,...,Firesat_Baseline,2025-08-29 03:55:11.682,2025-08-29 03:55:11.548,2069-12-25 12:18:56,-133.825752,73.286459,72.0,baseline,Firesat_Baseline_1_72.0_0,baseline
1,60,2025,1,0,12,19,15,1.27998,-2.33750,900029,...,Firesat_Baseline,2025-08-29 03:55:11.682,2025-08-29 03:55:11.548,2069-12-25 12:18:57,-133.928885,73.337452,72.0,baseline,Firesat_Baseline_1_72.0_0,baseline
2,61,2025,1,0,12,19,16,1.28087,-2.33930,900029,...,Firesat_Baseline,2025-08-29 03:55:11.682,2025-08-29 03:55:11.548,2069-12-25 12:18:58,-134.032017,73.388445,72.0,baseline,Firesat_Baseline_1_72.0_0,baseline
3,62,2025,1,0,12,19,17,1.28175,-2.34112,900028,...,Firesat_Baseline,2025-08-29 03:55:11.682,2025-08-29 03:55:11.548,2069-12-25 12:18:59,-134.136295,73.438865,72.0,baseline,Firesat_Baseline_1_72.0_0,baseline
4,63,2025,1,0,12,19,18,1.28264,-2.34295,900024,...,Firesat_Baseline,2025-08-29 03:55:11.682,2025-08-29 03:55:11.548,2069-12-25 12:19:00,-134.241147,73.489859,72.0,baseline,Firesat_Baseline_1_72.0_0,baseline

In [72]:
for col in sample_baseline_df.columns:
    print(f"{col} ({sample_baseline_df[col].dtype}): {sample_baseline_df[col].values[:5]})")
    # burada örnek baseline csv dosyasına ait  her bir column ve içlerindeki ilk 5 örneği yazdırdım.

FswTime(sec) (int64): [59 60 61 62 63])
CurrentYear(year) (int64): [2025 2025 2025 2025 2025])
CurrentMonth(month) (int64): [1 1 1 1 1])
CurrentDay(day) (int64): [0 0 0 0 0])
CurrentHour(hour) (int64): [12 12 12 12 12])
CurrentMinute(min) (int64): [19 19 19 19 19])
CurrentSecond(sec) (int64): [14 15 16 17 18])
Latitude(rad) (float64): [1.27909 1.27998 1.28087 1.28175 1.28264])
Longitude(rad) (float64): [-2.3357  -2.3375  -2.3393  -2.34112 -2.34295])
Altitude(m) (int64): [900032 900029 900029 900028 900024])
RawPrimaryGenericPointData[0]() (float64): [76.5311 76.5311 76.5311 76.5311 76.5311])
RawPrimaryGenericPointData[1]() (float64): [-68.5336 -68.5336 -68.5336 -68.5336 -68.5336])
RawPrimaryGenericPointData[2]() (float64): [102. 102. 102. 102. 102.])
RawSecondaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
Q_B_I[0](1) (float64): [0.536503 0.534079 0.531879 0.529741 0.527846])
Q_B_I[1](1) (float64): [0.820855 0.821888 0.822839 0.823886 0.824805])
Q_B_I[2](1) (float64): [ 0.0115042   0.00109952 -0.00730797 -0.0148703  -0.0215289 ])
Q_B_I[3](1) (float64): [0.195523 0.198138 0.199969 0.200911 0.201526])
Q_E_I[0](1) (float64): [0.797746 0.797768 0.79779  0.797812 0.797834])
Q_E_I[1](1) (float64): [-0.00072964 -0.0007296  -0.00072957 -0.00072953 -0.0007295 ])
Q_E_I[2](1) (float64): [0.00097098 0.00097101 0.00097103 0.00097106 0.00097109])
Q_E_I[3](1) (float64): [-0.602993 -0.602964 -0.602935 -0.602905 -0.602876])
SensedPos_I__GPS[0](m) (float64): [-1831260. -1824080. -1816910. -1809760. -1802580.])
SensedPos_I__GPS[1](m) (float64): [982433. 982707. 982967. 983240. 983515.])
SensedPos_I__GPS[2](m) (float64): [6975170. 6977010. 6978850. 6980650. 6982490.])
SensedVel_I__GPS[0](m/sec) (float64): [7162.12 7163.88 7165.37 7167.65 7169.21])
SensedVel_I__GPS[1](m/sec) (float64): [270.385 269.441 268.483 267.567 266.298])
SensedVel_I__GPS[2](m/sec) (float64): [1842.89 1835.91 1828.14 1821.71 1814.54])
AttitudeError[0](rad) (float64): [-0.0141363  -0.0127486  -0.0110617  -0.00896872 -0.00705425])
AttitudeError[1](rad) (float64): [0.0298081 0.0261315 0.0233371 0.0199636 0.0170526])
AttitudeError[2](rad) (float64): [0.0984574 0.122795  0.14311   0.161257  0.17766  ])
AngVel_B_I[0](rad/sec) (float64): [0.00129221 0.00140758 0.00146331 0.00146756 0.00142178])
AngVel_B_I[1](rad/sec) (float64): [-0.00763798 -0.0071212  -0.00667299 -0.00629744 -0.00594297])
AngVel_B_I[2](rad/sec) (float64): [0.0215813 0.0187803 0.0159792 0.0131782 0.0103771])
AngVelMag_B_I(rad/sec) (float64): [0.0229295 0.0201343 0.0173783 0.0146791 0.0120426])
LastNewWheelTime__RWA_A(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_B(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_C(sec) (int64): [59 60 61 62 63])
SensedWheelSpeed__RWA_A(rad/sec) (float64): [-4.91096 -5.34093 -5.54991 -5.56811 -5.40092])
SensedWheelSpeed__RWA_B(rad/sec) (float64): [16.9608 15.8133 14.8179 13.9837 13.196 ])
SensedWheelSpeed__RWA_C(rad/sec) (float64): [-79.9756 -69.5998 -59.224  -48.8482 -38.4724])
WheelCmd__RWA_A(N*m) (float64): [ 9.33445e-03  4.38036e-03  9.72342e-05 -4.11631e-03 -6.61577e-03])
WheelCmd__RWA_B(N*m) (float64): [0.030917  0.0271834 0.0232471 0.0221639 0.020337 ])
WheelCmd__RWA_C(N*m) (float64): [-0.21 -0.21 -0.21 -0.21 -0.21])
DesiredWheelCommand[0](N*m) (float64): [-0.00934561 -0.00438999 -0.0001056   0.00410899  0.00660936])
DesiredWheelCommand[1](N*m) (float64): [-0.0308635 -0.0271361 -0.0232062 -0.0221297 -0.0203097])
DesiredWheelCommand[2](N*m) (float64): [0.721702 0.715693 0.702029 0.682444 0.662499])
WheelSpeedReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_C(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_C(1) (int64): [0 0 0 0 0])
TotalTorqueRodCommand[0](A*m^2) (float64): [-0.00059835 -0.00059639 -0.00059978 -0.00060836 -0.00062243])
TotalTorqueRodCommand[1](A*m^2) (float64): [0.00166079 0.00170541 0.00174983 0.00179291 0.00183508])
TotalTorqueRodCommand[2](A*m^2) (float64): [0.00187375 0.00190463 0.00193533 0.00196488 0.00199412])
Pos_I[0](m) (float64): [-1831240. -1824080. -1816920. -1809750. -1802580.])
Pos_I[1](m) (float64): [982438. 982706. 982974. 983239. 983507.])
Pos_I[2](m) (float64): [6975180. 6977010. 6978840. 6980670. 6982480.])
Vel_I[0](m/sec) (float64): [7162.24 7164.08 7165.97 7167.85 7169.7 ])
Vel_I[1](m/sec) (float64): [270.507 269.477 268.457 267.419 266.413])
Vel_I[2](m/sec) (float64): [1842.36 1835.11 1827.9  1820.68 1813.42])
ExtrapolatedPos_I[0](m) (float64): [-1831260. -1824080. -1816910. -1809760. -1802580.])
ExtrapolatedPos_I[1](m) (float64): [982433. 982707. 982967. 983240. 983515.])
ExtrapolatedPos_I[2](m) (float64): [6975170. 6977010. 6978850. 6980650. 6982490.])
ExtrapolatedVel_I[0](m/sec) (float64): [7162.12 7163.88 7165.37 7167.65 7169.21])
ExtrapolatedVel_I[1](m/sec) (float64): [270.385 269.441 268.483 267.567 266.298])
ExtrapolatedVel_I[2](m/sec) (float64): [1842.89 1835.91 1828.14 1821.71 1814.54])
SemiMajorAxis(m) (float64): [7277980. 7277860. 7277870. 7277890. 7277820.])
Eccentricity(1) (float64): [2.93775e-05 4.35434e-05 4.14951e-05 3.91812e-05 4.68290e-05])
Inclination(deg) (float64): [98.0385 98.0385 98.0384 98.0384 98.0384])
Raan(deg) (float64): [-179.917 -179.918 -179.918 -179.918 -179.918])
ArgPerigee(deg) (float64): [-75.1835 -91.9187 -90.3977 -90.8096 -99.1156])
TrueAnomaly(deg) (float64): [150.622 167.416 165.953 166.423 174.787])
Mode() (int64): [8 8 8 8 8])
TrackerValid__ST() (int64): [1 1 1 1 1])
GpsTime__GPS(sec) (int64): [1419769154 1419769155 1419769156 1419769157 1419769158])
GpsSeconds__GPS(msec) (int64): [303554 303555 303556 303557 303558])
GpsWeek__GPS() (int64): [2347 2347 2347 2347 2347])
StateOfCharge__BAT(A*hr) (int64): [519571 519571 519571 519571 519571])
PercentSoC__BAT(1) (float64): [0.800473 0.800473 0.800473 0.800473 0.800473])
DepthOfDischarge__BAT(1) (float64): [0.199527 0.199527 0.199527 0.199527 0.199527])
IncomingCharge__BAT(W) (float64): [0. 0. 0. 0. 0.])
InEclipse() (int64): [0 0 0 0 0])
TotalLoad__BAT(W) (float64): [0. 0. 0. 0. 0.])
IMUAccMag__IMU(m/sec^2) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[0](1) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[1](1) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[2](1) (int64): [0 0 0 0 0])
IMURate_B__IMU[0](rad/sec) (float64): [0.00129221 0.00140758 0.00146331 0.00146756 0.00142178])
IMURate_B__IMU[1](rad/sec) (float64): [-0.00763798 -0.0071212  -0.00667299 -0.00629744 -0.00594297])
IMURate_B__IMU[2](rad/sec) (float64): [0.0215813 0.0187803 0.0159792 0.0131782 0.0103771])
IMURateMag__IMU(rad/sec) (float64): [0.0229295 0.0201343 0.0173783 0.0146791 0.0120426])
IMURateValid__IMU() (int64): [1 1 1 1 1])
LastNewAccTime__IMU(sec) (int64): [0 0 0 0 0])
LastNewTrackerTime__ST(sec) (float64): [59. 60. 61. 62. 63.])
TrackerRateMag__ST(rad/sec) (float64): [0.0241745 0.0220949 0.0178641 0.0159682 0.0140216])
TrackerQ_J_ST__ST[0](1) (float64): [0.432879 0.436861 0.439881 0.442468 0.444734])
TrackerQ_J_ST__ST[1](1) (float64): [-0.560258 -0.559604 -0.559333 -0.55965  -0.56005 ])
TrackerQ_J_ST__ST[2](1) (float64): [-0.317149 -0.307236 -0.299087 -0.291666 -0.285124])
TrackerQ_J_ST__ST[3](1) (float64): [-0.630986 -0.633721 -0.635766 -0.637138 -0.638169])
BField_B__TAM[0](T) (float64): [-3.12677e-06 -3.61121e-06 -4.02063e-06 -4.35375e-06 -4.61002e-06])
BField_B__TAM[1](T) (float64): [-3.05971e-05 -3.04986e-05 -3.03984e-05 -3.03015e-05 -3.02124e-05])
BField_B__TAM[2](T) (float64): [2.61212e-05 2.61778e-05 2.62386e-05 2.63014e-05 2.63639e-05])
BField_MAG__TAM[0](T) (float64): [-3.12677e-06 -3.61121e-06 -4.02063e-06 -4.35375e-06 -4.61002e-06])
BField_MAG__TAM[1](T) (float64): [3.05971e-05 3.04986e-05 3.03984e-05 3.03015e-05 3.02124e-05])
BField_MAG__TAM[2](T) (float64): [-2.61212e-05 -2.61778e-05 -2.62386e-05 -2.63014e-05 -2.63639e-05])
LastNewMagTime__TAM(sec) (int64): [59 60 61 62 63])
SunBetaAngle(rad) (float64): [-0.991183 -0.991183 -0.991183 -0.991183 -0.991183])
SunUnit_B[0](1) (float64): [-0.145862 -0.138698 -0.132337 -0.125335 -0.118778])
SunUnit_B[1](1) (float64): [-0.00111245  0.0028067   0.00634657  0.00979569  0.0127322 ])
SunUnit_B[2](1) (float64): [0.989304 0.990331 0.991184 0.992066 0.992839])
SunSensorIsGood__MX_SN07_32() (int64): [0 0 0 0 0])
SunSensorIsGood__MXPYPZ_SN07_29() (int64): [0 0 0 0 0])
SunSensorIsGood__MXMYPZ_SN07_29() (int64): [0 0 0 0 0])
SunSensorIsGood__MXMYMZ_SN07_30() (int64): [0 0 0 0 0])
SunSensorIsGood__MXPYMZ_SN07_21() (int64): [0 0 0 0 0])
SunSensorIsGood__PX_SN07_25() (int64): [0 0 0 0 0])
SunSensorIsGood__MXPYPZ_SN07_34() (int64): [0 0 0 0 0])
SunSensorIsGood__PXMYPZ_SN07_33() (int64): [0 0 0 0 0])
SunSensorIsGood__PXMYMZ_SN07_22() (int64): [0 0 0 0 0])
SunSensorIsGood__PXPYMZ_SN07_28() (int64): [0 0 0 0 0])
TrackerDataIsGood__ST() (int64): [1 1 1 1 1])
TrackerRateIsGood__ST() (int64): [1 1 1 1 1])
MagDataIsGood__TAM() (int64): [1 1 1 1 1])
LastNewGpsTime__GPS(sec) (int64): [59 60 61 62 63])
AngleToPrimaryTarget(rad) (float64): [0.0329917 0.0290765 0.0258267 0.0218862 0.0184543])
Variant (object): ['1_72.0_0' '1_72.0_0' '1_72.0_0' '1_72.0_0' '1_72.0_0'])
Run_Batch (object): ['Firesat_Baseline' 'Firesat_Baseline' 'Firesat_Baseline'
 'Firesat_Baseline' 'Firesat_Baseline'])
date_loaded (object): ['2025-08-29 03:55:11.682' '2025-08-29 03:55:11.682'
 '2025-08-29 03:55:11.682' '2025-08-29 03:55:11.682'
 '2025-08-29 03:55:11.682'])
date_created (object): ['2025-08-29 03:55:11.548' '2025-08-29 03:55:11.548'
 '2025-08-29 03:55:11.548' '2025-08-29 03:55:11.548'
 '2025-08-29 03:55:11.548'])
UTC (object): ['2069-12-25 12:18:56' '2069-12-25 12:18:57' '2069-12-25 12:18:58'
 '2069-12-25 12:18:59' '2069-12-25 12:19:00'])
Longitude(deg) (float64): [-133.82575221 -133.92888461 -134.03201701 -134.13629533 -134.24114661])
Latitude(deg) (float64): [73.28645862 73.33745186 73.3884451  73.43886539 73.48985863])
TimeDelay (float64): [72. 72. 72. 72. 72.])
Scenario (object): ['baseline' 'baseline' 'baseline' 'baseline' 'baseline'])
Run_Batch_Variant (object): ['Firesat_Baseline_1_72.0_0' 'Firesat_Baseline_1_72.0_0'
 'Firesat_Baseline_1_72.0_0' 'Firesat_Baseline_1_72.0_0'
 'Firesat_Baseline_1_72.0_0'])
result_label (object): ['baseline' 'baseline' 'baseline' 'baseline' 'baseline'])

In [73]:
#örnek attack_rwa csv dosyası içeriği:
sample_attack_rwa_df = pd.read_csv(BASE / "attack_rwa/fsw_data_2_180.0_-25.csv")
sample_attack_rwa_df.head()

,FswTime(sec),CurrentYear(year),CurrentMonth(month),CurrentDay(day),CurrentHour(hour),CurrentMinute(min),CurrentSecond(sec),Latitude(rad),Longitude(rad),Altitude(m),...,date_loaded,date_created,UTC,Longitude(deg),Latitude(deg),TimeDelay,AttackIntensity,Scenario,Run_Batch_Variant,result_label
0,59,2025,2,0,12,46,14,-0.056990,0.636108,899984,...,2025-08-28 19:40:04.227,2025-08-28 19:40:04.087,2070-02-22 12:45:56,36.446304,-3.265275,180.0,-25.0,attack_rwa,Firesat_Attack_RWA_2_180.0_-25,baseline
1,60,2025,2,0,12,46,15,-0.057998,0.635892,899991,...,2025-08-28 19:40:04.227,2025-08-28 19:40:04.087,2070-02-22 12:45:57,36.433928,-3.323012,180.0,-25.0,attack_rwa,Firesat_Attack_RWA_2_180.0_-25,baseline
2,61,2025,2,0,12,46,16,-0.059005,0.635675,899987,...,2025-08-28 19:40:04.227,2025-08-28 19:40:04.087,2070-02-22 12:45:58,36.421495,-3.380715,180.0,-25.0,attack_rwa,Firesat_Attack_RWA_2_180.0_-25,baseline
3,62,2025,2,0,12,46,17,-0.060012,0.635460,899994,...,2025-08-28 19:40:04.227,2025-08-28 19:40:04.087,2070-02-22 12:45:59,36.409176,-3.438406,180.0,-25.0,attack_rwa,Firesat_Attack_RWA_2_180.0_-25,baseline
4,63,2025,2,0,12,46,18,-0.061018,0.635245,899993,...,2025-08-28 19:40:04.227,2025-08-28 19:40:04.087,2070-02-22 12:46:00,36.396857,-3.496062,180.0,-25.0,attack_rwa,Firesat_Attack_RWA_2_180.0_-25,baseline

In [74]:
for col in sample_attack_rwa_df.columns:
    print(f"{col} ({sample_attack_rwa_df[col].dtype}): {sample_attack_rwa_df[col].values[:5]})")
    # burada örnek attack_rwa csv dosyasına ait  her bir column ve içlerindeki ilk 5 örneği yazdırdım.

FswTime(sec) (int64): [59 60 61 62 63])
CurrentYear(year) (int64): [2025 2025 2025 2025 2025])
CurrentMonth(month) (int64): [2 2 2 2 2])
CurrentDay(day) (int64): [0 0 0 0 0])
CurrentHour(hour) (int64): [12 12 12 12 12])
CurrentMinute(min) (int64): [46 46 46 46 46])
CurrentSecond(sec) (int64): [14 15 16 17 18])
Latitude(rad) (float64): [-0.0569898 -0.0579975 -0.0590046 -0.0600115 -0.0610178])
Longitude(rad) (float64): [0.636108 0.635892 0.635675 0.63546  0.635245])
Altitude(m) (int64): [899984 899991 899987 899994 899993])
RawPrimaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawPrimaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawPrimaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
Q_B_I[0](1) (float64): [0.391792 0.393613 0.395538 0.396945 0.398386])
Q_B_I[1](1) (float64): [-0.0831311 -0.0718655 -0.0603115 -0.0475359 -0.0348742])
Q_B_I[2](1) (float64): [-0.526831 -0.505584 -0.483015 -0.458848 -0.433369])
Q_B_I[3](1) (float64): [0.749691 0.764388 0.778851 0.793494 0.807629])
Q_E_I[0](1) (float64): [0.948747 0.948758 0.94877  0.948781 0.948793])
Q_E_I[1](1) (float64): [-0.00038187 -0.00038183 -0.00038179 -0.00038175 -0.00038171])
Q_E_I[2](1) (float64): [0.00115732 0.00115733 0.00115735 0.00115736 0.00115737])
Q_E_I[3](1) (float64): [-0.316035 -0.316001 -0.315966 -0.315931 -0.315897])
SensedPos_I__GPS[0](m) (float64): [7265120. 7264640. 7264210. 7263750. 7263260.])
SensedPos_I__GPS[1](m) (float64): [-50762.6 -51835.7 -52843.9 -53866.8 -54913.9])
SensedPos_I__GPS[2](m) (float64): [-432280. -439588. -446908. -454204. -461535.])
SensedVel_I__GPS[0](m/sec) (float64): [-443.075 -450.284 -457.743 -465.537 -473.113])
SensedVel_I__GPS[1](m/sec) (float64): [-1033.59 -1033.49 -1033.54 -1033.59 -1033.51])
SensedVel_I__GPS[2](m/sec) (float64): [-7314.78 -7314.1  -7313.64 -7313.21 -7312.78])
AttitudeError[0](rad) (float64): [-0.861249 -0.811082 -0.75842  -0.701799 -0.643081])
AttitudeError[1](rad) (float64): [0.00418365 0.00370037 0.00371128 0.00263082 0.00268894])
AttitudeError[2](rad) (float64): [0.00061416 0.00122863 0.0011317  0.00143439 0.00106229])
AngVel_B_I[0](rad/sec) (float64): [0.0548634 0.0576644 0.0604655 0.0632665 0.0644675])
AngVel_B_I[1](rad/sec) (float64): [-0.00054152 -0.00048865 -0.00043874 -0.00040867 -0.00035084])
AngVel_B_I[2](rad/sec) (float64): [ 9.56459e-05  5.74546e-05  1.44207e-05 -1.54723e-05 -4.47861e-05])
AngVelMag_B_I(rad/sec) (float64): [0.0548661 0.0576665 0.0604671 0.0632679 0.0644684])
LastNewWheelTime__RWA_A(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_B(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_C(sec) (int64): [59 60 61 62 63])
SensedWheelSpeed__RWA_A(rad/sec) (float64): [-203.239 -213.615 -223.991 -234.366 -238.814])
SensedWheelSpeed__RWA_B(rad/sec) (float64): [1.16931  1.0473   0.931595 0.859748 0.726022])
SensedWheelSpeed__RWA_C(rad/sec) (float64): [-0.426334  -0.285223  -0.125859  -0.014816   0.0944349])
WheelCmd__RWA_A(N*m) (float64): [ 0.21       0.21       0.21       0.0982275 -0.0444174])
WheelCmd__RWA_B(N*m) (float64): [0.00295292 0.00280217 0.00172554 0.00324977 0.0019153 ])
WheelCmd__RWA_C(N*m) (float64): [-0.00319894 -0.00361675 -0.002509   -0.00247624 -0.00110704])
DesiredWheelCommand[0](N*m) (float64): [-0.594014  -0.434667  -0.270451  -0.0982281  0.044417 ])
DesiredWheelCommand[1](N*m) (float64): [-0.00303291 -0.00288667 -0.00181421 -0.00334216 -0.00200857])
DesiredWheelCommand[2](N*m) (float64): [0.003237   0.00366202 0.0025623  0.00253843 0.00117718])
WheelSpeedReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_C(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_C(1) (int64): [0 0 0 0 0])
TotalTorqueRodCommand[0](A*m^2) (float64): [-0.00161295 -0.00166104 -0.00170991 -0.00175933 -0.00180929])
TotalTorqueRodCommand[1](A*m^2) (float64): [-2.31629e-05 -4.04678e-05 -6.05366e-05 -8.34323e-05 -1.08816e-04])
TotalTorqueRodCommand[2](A*m^2) (float64): [-0.00022084 -0.00024137 -0.00026031 -0.00027737 -0.00029215])
Pos_I[0](m) (float64): [7265100. 7264660. 7264200. 7263740. 7263270.])
Pos_I[1](m) (float64): [-50773.4 -51806.7 -52851.5 -53879.8 -54908.5])
Pos_I[2](m) (float64): [-432264. -439585. -446901. -454216. -461525.])
Vel_I[0](m/sec) (float64): [-442.548 -450.014 -457.555 -465.018 -472.526])
Vel_I[1](m/sec) (float64): [-1033.57 -1033.52 -1033.54 -1033.45 -1033.36])
Vel_I[2](m/sec) (float64): [-7314.37 -7313.97 -7313.53 -7313.07 -7312.58])
ExtrapolatedPos_I[0](m) (float64): [7265120. 7264640. 7264210. 7263750. 7263260.])
ExtrapolatedPos_I[1](m) (float64): [-50762.6 -51835.7 -52843.9 -53866.9 -54913.9])
ExtrapolatedPos_I[2](m) (float64): [-432280. -439588. -446908. -454204. -461535.])
ExtrapolatedVel_I[0](m/sec) (float64): [-443.075 -450.284 -457.743 -465.537 -473.114])
ExtrapolatedVel_I[1](m/sec) (float64): [-1033.59 -1033.49 -1033.54 -1033.59 -1033.51])
ExtrapolatedVel_I[2](m/sec) (float64): [-7314.78 -7314.1  -7313.64 -7313.21 -7312.78])
SemiMajorAxis(m) (float64): [7277750. 7277860. 7277900. 7277920. 7277860.])
Eccentricity(1) (float64): [5.39744e-05 3.85543e-05 3.31488e-05 3.00972e-05 3.73396e-05])
Inclination(deg) (float64): [98.0382 98.0382 98.0388 98.0385 98.0382])
Raan(deg) (float64): [-179.919 -179.919 -179.919 -179.919 -179.919])
ArgPerigee(deg) (float64): [-15.4191  -11.6503  -20.3453   -9.86177  -8.07885])
TrueAnomaly(deg) (float64): [-161.142 -164.853 -156.099 -166.525 -168.249])
Mode() (int64): [4 4 4 4 4])
TrackerValid__ST() (int64): [1 1 1 1 1])
GpsTime__GPS(sec) (int64): [1422449174 1422449175 1422449176 1422449177 1422449178])
GpsSeconds__GPS(msec) (int64): [564374 564375 564376 564377 564378])
GpsWeek__GPS() (int64): [2351 2351 2351 2351 2351])
StateOfCharge__BAT(A*hr) (int64): [521575 521610 521645 521679 521714])
PercentSoC__BAT(1) (float64): [0.80356  0.803614 0.803668 0.803721 0.803775])
DepthOfDischarge__BAT(1) (float64): [0.19644  0.196386 0.196332 0.196279 0.196225])
IncomingCharge__BAT(W) (float64): [441.421 441.421 441.421 441.42  441.42 ])
InEclipse() (int64): [1 1 1 1 1])
TotalLoad__BAT(W) (float64): [23.3333 23.3333 23.3333 23.3333 23.3333])
IMUAccMag__IMU(m/sec^2) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[0](1) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[1](1) (int64): [0 0 0 0 0])
IMUAccUnit__IMU[2](1) (int64): [0 0 0 0 0])
IMURate_B__IMU[0](rad/sec) (float64): [0.0548634 0.0576644 0.0604655 0.0632665 0.0644675])
IMURate_B__IMU[1](rad/sec) (float64): [-0.00054152 -0.00048865 -0.00043874 -0.00040867 -0.00035084])
IMURate_B__IMU[2](rad/sec) (float64): [ 9.56459e-05  5.74546e-05  1.44207e-05 -1.54723e-05 -4.47861e-05])
IMURateMag__IMU(rad/sec) (float64): [0.0548661 0.0576665 0.0604671 0.0632679 0.0644684])
IMURateValid__IMU() (int64): [1 1 1 1 1])
LastNewAccTime__IMU(sec) (int64): [0 0 0 0 0])
LastNewTrackerTime__ST(sec) (float64): [59. 60. 61. 62. 63.])
TrackerRateMag__ST(rad/sec) (float64): [0.0539751 0.0564877 0.0585099 0.0620873 0.0636076])
TrackerQ_J_ST__ST[0](1) (float64): [0.623116 0.61242  0.601052 0.588343 0.574909])
TrackerQ_J_ST__ST[1](1) (float64): [0.498102 0.497304 0.496135 0.494069 0.491804])
TrackerQ_J_ST__ST[2](1) (float64): [0.206832 0.188383 0.168791 0.148188 0.12649 ])
TrackerQ_J_ST__ST[3](1) (float64): [-0.566429 -0.584929 -0.603404 -0.622727 -0.641568])
BField_B__TAM[0](T) (float64): [-8.80490e-07 -9.21163e-07 -9.61063e-07 -1.00027e-06 -1.03911e-06])
BField_B__TAM[1](T) (float64): [-1.93281e-05 -1.88437e-05 -1.82737e-05 -1.76111e-05 -1.68590e-05])
BField_B__TAM[2](T) (float64): [8.45797e-06 9.49858e-06 1.05628e-05 1.16422e-05 1.27146e-05])
BField_MAG__TAM[0](T) (float64): [-8.80490e-07 -9.21163e-07 -9.61063e-07 -1.00027e-06 -1.03911e-06])
BField_MAG__TAM[1](T) (float64): [1.93281e-05 1.88437e-05 1.82737e-05 1.76111e-05 1.68590e-05])
BField_MAG__TAM[2](T) (float64): [-8.45797e-06 -9.49858e-06 -1.05628e-05 -1.16422e-05 -1.27146e-05])
LastNewMagTime__TAM(sec) (int64): [59 60 61 62 63])
SunBetaAngle(rad) (float64): [-0.67688  -0.676881 -0.676875 -0.676877 -0.676879])
SunUnit_B[0](1) (float64): [-0.999991 -0.999992 -0.999992 -0.999996 -0.999996])
SunUnit_B[1](1) (float64): [0.00235588 0.00262371 0.00245453 0.00226633 0.00187048])
SunUnit_B[2](1) (float64): [-0.00351139 -0.00288416 -0.00300493 -0.00196021 -0.00220457])
SunSensorIsGood__MX_SN07_32() (int64): [0 0 0 2 2])
SunSensorIsGood__MXPYPZ_SN07_29() (int64): [2 2 2 2 2])
SunSensorIsGood__MXMYPZ_SN07_29() (int64): [2 2 2 2 2])
SunSensorIsGood__MXMYMZ_SN07_30() (int64): [2 2 2 2 2])
SunSensorIsGood__MXPYMZ_SN07_21() (int64): [2 2 2 2 2])
SunSensorIsGood__PX_SN07_25() (int64): [0 0 0 0 0])
SunSensorIsGood__MXPYPZ_SN07_34() (int64): [0 0 0 0 0])
SunSensorIsGood__PXMYPZ_SN07_33() (int64): [0 0 0 0 0])
SunSensorIsGood__PXMYMZ_SN07_22() (int64): [0 0 0 0 0])
SunSensorIsGood__PXPYMZ_SN07_28() (int64): [0 0 0 0 0])
TrackerDataIsGood__ST() (int64): [1 1 1 1 1])
TrackerRateIsGood__ST() (int64): [1 1 1 1 1])
MagDataIsGood__TAM() (int64): [1 1 1 1 1])
LastNewGpsTime__GPS(sec) (int64): [59 60 61 62 63])
AngleToPrimaryTarget(rad) (float64): [0.00422849 0.00389902 0.00388    0.00299645 0.00289117])
Variant (object): ['2_180.0_-25' '2_180.0_-25' '2_180.0_-25' '2_180.0_-25' '2_180.0_-25'])
Run_Batch (object): ['Firesat_Attack_RWA' 'Firesat_Attack_RWA' 'Firesat_Attack_RWA'
 'Firesat_Attack_RWA' 'Firesat_Attack_RWA'])
date_loaded (object): ['2025-08-28 19:40:04.227' '2025-08-28 19:40:04.227'
 '2025-08-28 19:40:04.227' '2025-08-28 19:40:04.227'
 '2025-08-28 19:40:04.227'])
date_created (object): ['2025-08-28 19:40:04.087' '2025-08-28 19:40:04.087'
 '2025-08-28 19:40:04.087' '2025-08-28 19:40:04.087'
 '2025-08-28 19:40:04.087'])
UTC (object): ['2070-02-22 12:45:56' '2070-02-22 12:45:57' '2070-02-22 12:45:58'
 '2070-02-22 12:45:59' '2070-02-22 12:46:00'])
Longitude(deg) (float64): [36.44630371 36.43392783 36.42149464 36.40917605 36.39685746])
Latitude(deg) (float64): [-3.26527502 -3.32301197 -3.38071455 -3.43840567 -3.49606242])
TimeDelay (float64): [180. 180. 180. 180. 180.])
AttackIntensity (float64): [-25. -25. -25. -25. -25.])
Scenario (object): ['attack_rwa' 'attack_rwa' 'attack_rwa' 'attack_rwa' 'attack_rwa'])
Run_Batch_Variant (object): ['Firesat_Attack_RWA_2_180.0_-25' 'Firesat_Attack_RWA_2_180.0_-25'
 'Firesat_Attack_RWA_2_180.0_-25' 'Firesat_Attack_RWA_2_180.0_-25'
 'Firesat_Attack_RWA_2_180.0_-25'])
result_label (object): ['baseline' 'baseline' 'baseline' 'baseline' 'baseline'])

In [75]:
#örnek attack_rwb csv dosyası içeriği:
sample_attack_rwb_df = pd.read_csv(BASE / "attack_rwb/fsw_data_3_72.0_50.csv")
for col in sample_attack_rwb_df.columns:
    print(f"{col} ({sample_attack_rwb_df[col].dtype}): {sample_attack_rwb_df[col].values[:5]})")
    # burada örnek attack_rwb csv dosyasına ait  her bir column ve içlerindeki ilk 5 örneği yazdırdım.

FswTime(sec) (int64): [59 60 61 62 63])
CurrentYear(year) (int64): [2025 2025 2025 2025 2025])
CurrentMonth(month) (int64): [3 3 3 3 3])
CurrentDay(day) (int64): [0 0 0 0 0])
CurrentHour(hour) (int64): [12 12 12 12 12])
CurrentMinute(min) (int64): [19 19 19 19 19])
CurrentSecond(sec) (int64): [14 15 16 17 18])
Latitude(rad) (float64): [1.27908 1.27997 1.28085 1.28174 1.28262])
Longitude(rad) (float64): [2.93258 2.93079 2.92898 2.92716 2.92534])
Altitude(m) (int64): [900031 900032 900029 900031 900033])
RawPrimaryGenericPointData[0]() (float64): [76.5311 76.5311 76.5311 76.5311 76.5311])
RawPrimaryGenericPointData[1]() (float64): [-68.5336 -68.5336 -68.5336 -68.5336 -68.5336])
RawPrimaryGenericPointData[2]() (float64): [102. 102. 102. 102. 102.])
RawSecondaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
Q_B_I[0](1) (float64): [0.150756 0.151449 0.152861 0.154918 0.158201])
Q_B_I[1](1) (float64): [-0.324071 -0.322146 -0.319013 -0.314922 -0.309737])
Q_B_I[2](1) (float64): [0.701938 0.704458 0.707266 0.7105   0.714274])
Q_B_I[3](1) (float64): [-0.616062 -0.614023 -0.612078 -0.60993  -0.607328])
Q_E_I[0](1) (float64): [0.990245 0.990251 0.990256 0.990261 0.990266])
Q_E_I[1](1) (float64): [-0.00016688 -0.00016683 -0.00016679 -0.00016675 -0.0001667 ])
Q_E_I[2](1) (float64): [0.00121097 0.00121098 0.00121098 0.00121099 0.001211  ])
Q_E_I[3](1) (float64): [-0.139329 -0.139293 -0.139256 -0.13922  -0.139184])
SensedPos_I__GPS[0](m) (float64): [-1831250. -1824090. -1816920. -1809760. -1802590.])
SensedPos_I__GPS[1](m) (float64): [982418. 982687. 982976. 983230. 983504.])
SensedPos_I__GPS[2](m) (float64): [6975180. 6977010. 6978840. 6980670. 6982490.])
SensedVel_I__GPS[0](m/sec) (float64): [7162.04 7163.84 7165.5  7167.47 7169.45])
SensedVel_I__GPS[1](m/sec) (float64): [270.511 269.658 268.59  267.617 266.431])
SensedVel_I__GPS[2](m/sec) (float64): [1843.12 1836.04 1828.56 1821.28 1814.29])
AttitudeError[0](rad) (float64): [0.048875  0.0450692 0.041957  0.0387746 0.0353137])
AttitudeError[1](rad) (float64): [0.00714017 0.00690038 0.0071019  0.00751204 0.00735247])
AttitudeError[2](rad) (float64): [-0.326503 -0.321607 -0.313982 -0.303898 -0.290323])
AngVel_B_I[0](rad/sec) (float64): [-0.00437606 -0.00460872 -0.00469079 -0.00467697 -0.0045903 ])
AngVel_B_I[1](rad/sec) (float64): [0.00109361 0.00114392 0.00118559 0.00120654 0.00120506])
AngVel_B_I[2](rad/sec) (float64): [0.00428284 0.00708431 0.00988577 0.0126872  0.0154886 ])
AngVelMag_B_I(rad/sec) (float64): [0.00622001 0.00852856 0.0110062  0.0135755  0.0161994 ])
LastNewWheelTime__RWA_A(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_B(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_C(sec) (int64): [59 60 61 62 63])
SensedWheelSpeed__RWA_A(rad/sec) (float64): [16.3207 17.1844 17.4902 17.4407 17.1214])
SensedWheelSpeed__RWA_B(rad/sec) (float64): [-2.42092 -2.53477 -2.62974 -2.67901 -2.6788 ])
SensedWheelSpeed__RWA_C(rad/sec) (float64): [-15.8297 -26.2055 -36.5813 -46.9571 -57.3329])
WheelCmd__RWA_A(N*m) (float64): [-0.0186809  -0.00605672  0.00193552  0.00800782  0.0131927 ])
WheelCmd__RWA_B(N*m) (float64): [ 0.00119035  0.00073673 -0.00037107 -0.00159784 -0.00113357])
WheelCmd__RWA_C(N*m) (float64): [0.21 0.21 0.21 0.21 0.21])
DesiredWheelCommand[0](N*m) (float64): [ 0.0186809   0.00605695 -0.00193541 -0.00800817 -0.0131939 ])
DesiredWheelCommand[1](N*m) (float64): [-0.00120305 -0.00075628  0.00034457  0.00156429  0.00109282])
DesiredWheelCommand[2](N*m) (float64): [-0.582409 -0.513397 -0.43904  -0.359827 -0.273501])
WheelSpeedReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_C(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_C(1) (int64): [0 0 0 0 0])
TotalTorqueRodCommand[0](A*m^2) (float64): [-0.0004165  -0.00048075 -0.00054942 -0.00062272 -0.00070093])
TotalTorqueRodCommand[1](A*m^2) (float64): [-0.00158416 -0.00162126 -0.00165691 -0.00168974 -0.00172014])
TotalTorqueRodCommand[2](A*m^2) (float64): [0.00166493 0.00167861 0.00169253 0.00170618 0.00172099])
Pos_I[0](m) (float64): [-1831250. -1824090. -1816920. -1809750. -1802590.])
Pos_I[1](m) (float64): [982433. 982695. 982962. 983235. 983500.])
Pos_I[2](m) (float64): [6975180. 6977020. 6978840. 6980670. 6982490.])
Vel_I[0](m/sec) (float64): [7162.14 7164.   7165.87 7167.75 7169.62])
Vel_I[1](m/sec) (float64): [270.365 269.297 268.271 267.291 266.262])
Vel_I[2](m/sec) (float64): [1842.46 1835.25 1828.01 1820.8  1813.6 ])
ExtrapolatedPos_I[0](m) (float64): [-1831250. -1824090. -1816920. -1809750. -1802590.])
ExtrapolatedPos_I[1](m) (float64): [982418. 982687. 982976. 983230. 983504.])
ExtrapolatedPos_I[2](m) (float64): [6975180. 6977010. 6978840. 6980670. 6982490.])
ExtrapolatedVel_I[0](m/sec) (float64): [7162.04 7163.84 7165.5  7167.47 7169.45])
ExtrapolatedVel_I[1](m/sec) (float64): [270.511 269.658 268.59  267.617 266.431])
ExtrapolatedVel_I[2](m/sec) (float64): [1843.12 1836.04 1828.56 1821.28 1814.29])
SemiMajorAxis(m) (float64): [7277810. 7277760. 7277730. 7277740. 7277750.])
Eccentricity(1) (float64): [5.56626e-05 6.23318e-05 6.42304e-05 6.32700e-05 6.29406e-05])
Inclination(deg) (float64): [98.0381 98.038  98.038  98.0381 98.038 ])
Raan(deg) (float64): [-179.919 -179.919 -179.919 -179.919 -179.919])
ArgPerigee(deg) (float64): [-75.558  -78.811  -82.912  -81.3003 -79.4886])
TrueAnomaly(deg) (float64): [150.997 154.308 158.467 156.914 155.16 ])
Mode() (int64): [8 8 8 8 8])
TrackerValid__ST() (int64): [1 1 1 1 1])
GpsTime__GPS(sec) (int64): [1424866754 1424866755 1424866756 1424866757 1424866758])
GpsSeconds__GPS(msec) (int64): [562754 562755 562756 562757 562758])
GpsWeek__GPS() (int64): [2355 2355 2355 2355 2355])
StateOfCharge__BAT(A*hr) (int64): [520950 520970 520989 521009 521029])
PercentSoC__BAT(1) (float64): [0.802597 0.802628 0.802658 0.802689 0.802719])
DepthOfDischarge__BAT(1) (float64): [0.197403 0.197372 0.197342 0.197311 0.197281])
IncomingCharge__BAT(W) (float64): [235.553 236.309 237.251 238.368 239.637])
InEclipse() (float64): [0. 0. 0. 0. 0.])
TotalLoad__BAT(W) (float64): [0. 0. 0. 0. 0.])
IMUAccMag__IMU(m/sec^2) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[0](1) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[1](1) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[2](1) (float64): [0. 0. 0. 0. 0.])
IMURate_B__IMU[0](rad/sec) (float64): [-0.00437606 -0.00460872 -0.00469079 -0.00467697 -0.0045903 ])
IMURate_B__IMU[1](rad/sec) (float64): [0.00109361 0.00114392 0.00118559 0.00120654 0.00120506])
IMURate_B__IMU[2](rad/sec) (float64): [0.00428284 0.00708431 0.00988577 0.0126872  0.0154886 ])
IMURateMag__IMU(rad/sec) (float64): [0.00622001 0.00852856 0.0110062  0.0135755  0.0161994 ])
IMURateValid__IMU() (float64): [1. 1. 1. 1. 1.])
LastNewAccTime__IMU(sec) (float64): [0. 0. 0. 0. 0.])
LastNewTrackerTime__ST(sec) (float64): [59. 60. 61. 62. 63.])
TrackerRateMag__ST(rad/sec) (float64): [0.00499205 0.00766527 0.00969291 0.0120067  0.0153183 ])
TrackerQ_J_ST__ST[0](1) (float64): [0.279123 0.280001 0.280455 0.280625 0.2801  ])
TrackerQ_J_ST__ST[1](1) (float64): [0.0878952 0.0883022 0.0897536 0.0918723 0.0946273])
TrackerQ_J_ST__ST[2](1) (float64): [0.661465 0.663925 0.667036 0.670865 0.675839])
TrackerQ_J_ST__ST[3](1) (float64): [-0.690528 -0.687754 -0.684363 -0.680257 -0.675153])
BField_B__TAM[0](T) (float64): [-9.54314e-06 -9.37437e-06 -9.12725e-06 -8.80108e-06 -8.39485e-06])
BField_B__TAM[1](T) (float64): [2.82980e-05 2.82832e-05 2.82886e-05 2.83152e-05 2.83621e-05])
BField_B__TAM[2](T) (float64): [2.45379e-05 2.46320e-05 2.47305e-05 2.48301e-05 2.49290e-05])
BField_MAG__TAM[0](T) (float64): [-9.54314e-06 -9.37437e-06 -9.12725e-06 -8.80108e-06 -8.39485e-06])
BField_MAG__TAM[1](T) (float64): [-2.82980e-05 -2.82832e-05 -2.82886e-05 -2.83152e-05 -2.83621e-05])
BField_MAG__TAM[2](T) (float64): [-2.45379e-05 -2.46320e-05 -2.47305e-05 -2.48301e-05 -2.49290e-05])
LastNewMagTime__TAM(sec) (float64): [59. 60. 61. 62. 63.])
SunBetaAngle(rad) (float64): [-0.281399 -0.281393 -0.281392 -0.281396 -0.281394])
SunUnit_B[0](1) (float64): [-0.538021 -0.539531 -0.541937 -0.544885 -0.547838])
SunUnit_B[1](1) (float64): [-0.139736 -0.140712 -0.139681 -0.137362 -0.133233])
SunUnit_B[2](1) (float64): [0.831268 0.830125 0.82873  0.827183 0.825907])
SunSensorIsGood__MX_SN07_32() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__MXPYPZ_SN07_29() (float64): [2. 1. 2. 2. 1.])
SunSensorIsGood__MXMYPZ_SN07_29() (float64): [2. 2. 2. 2. 2.])
SunSensorIsGood__MXMYMZ_SN07_30() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__MXPYMZ_SN07_21() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PX_SN07_25() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__MXPYPZ_SN07_34() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXMYPZ_SN07_33() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXMYMZ_SN07_22() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXPYMZ_SN07_28() (float64): [0. 0. 0. 0. 0.])
TrackerDataIsGood__ST() (float64): [1. 1. 1. 1. 1.])
TrackerRateIsGood__ST() (float64): [1. 1. 1. 1. 1.])
MagDataIsGood__TAM() (float64): [1. 1. 1. 1. 1.])
LastNewGpsTime__GPS(sec) (float64): [59. 60. 61. 62. 63.])
AngleToPrimaryTarget(rad) (float64): [0.0493988 0.0455984 0.042557  0.0394981 0.0360729])
Variant (object): ['3_72.0_50' '3_72.0_50' '3_72.0_50' '3_72.0_50' '3_72.0_50'])
Run_Batch (object): ['Firesat_Attack_RWB' 'Firesat_Attack_RWB' 'Firesat_Attack_RWB'
 'Firesat_Attack_RWB' 'Firesat_Attack_RWB'])
date_loaded (object): ['2025-08-28 21:53:34.327' '2025-08-28 21:53:34.327'
 '2025-08-28 21:53:34.327' '2025-08-28 21:53:34.327'
 '2025-08-28 21:53:34.327'])
date_created (object): ['2025-08-28 21:53:34.202' '2025-08-28 21:53:34.202'
 '2025-08-28 21:53:34.202' '2025-08-28 21:53:34.202'
 '2025-08-28 21:53:34.202'])
UTC (object): ['2070-04-19 12:18:56' '2070-04-19 12:18:57' '2070-04-19 12:18:58'
 '2070-04-19 12:18:59' '2070-04-19 12:19:00'])
Longitude(deg) (float64): [168.02445708 167.92189764 167.81819228 167.71391396 167.60963564])
Latitude(deg) (float64): [73.28588566 73.3368789  73.38729919 73.43829243 73.48871272])
TimeDelay (float64): [72. 72. 72. 72. 72.])
AttackIntensity (float64): [50. 50. 50. 50. 50.])
Scenario (object): ['attack_rwb' 'attack_rwb' 'attack_rwb' 'attack_rwb' 'attack_rwb'])
Run_Batch_Variant (object): ['Firesat_Attack_RWB_3_72.0_50' 'Firesat_Attack_RWB_3_72.0_50'
 'Firesat_Attack_RWB_3_72.0_50' 'Firesat_Attack_RWB_3_72.0_50'
 'Firesat_Attack_RWB_3_72.0_50'])
result_label (object): ['baseline' 'baseline' 'baseline' 'baseline' 'baseline'])

In [76]:
#örnek attack_rwc csv dosyası içeriği:
sample_attack_rwc_df = pd.read_csv(BASE / "attack_rwc/fsw_data_12_324.0_0.csv")
for col in sample_attack_rwc_df.columns:
    print(f"{col} ({sample_attack_rwc_df[col].dtype}): {sample_attack_rwc_df[col].values[:5]})")
    # burada örnek attack_rwc csv dosyasına ait  her bir column ve içlerindeki ilk 5 örneği yazdırdım.

FswTime(sec) (int64): [59 60 61 62 63])
CurrentYear(year) (int64): [2025 2025 2025 2025 2025])
CurrentMonth(month) (int64): [12 12 12 12 12])
CurrentDay(day) (int64): [1 1 1 1 1])
CurrentHour(hour) (int64): [13 13 13 13 13])
CurrentMinute(min) (int64): [22 22 22 22 22])
CurrentSecond(sec) (int64): [14 15 16 17 18])
Latitude(rad) (float64): [-0.564544 -0.563542 -0.562539 -0.561536 -0.560533])
Longitude(rad) (float64): [-1.49446 -1.49474 -1.49501 -1.49528 -1.49555])
Altitude(m) (int64): [900007 900009 900007 900005 900000])
RawPrimaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawPrimaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawPrimaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[0]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[1]() (float64): [0. 0. 0. 0. 0.])
RawSecondaryGenericPointData[2]() (float64): [0. 0. 0. 0. 0.])
Q_B_I[0](1) (float64): [0.443103 0.42018  0.39567  0.37006  0.343323])
Q_B_I[1](1) (float64): [0.691321 0.705326 0.719452 0.733225 0.746082])
Q_B_I[2](1) (float64): [0.31764  0.333234 0.349119 0.364585 0.380013])
Q_B_I[3](1) (float64): [0.474173 0.463593 0.451609 0.438766 0.425536])
Q_E_I[0](1) (float64): [0.712139 0.712164 0.71219  0.712216 0.712241])
Q_E_I[1](1) (float64): [-0.00088124 -0.00088121 -0.00088117 -0.00088114 -0.00088111])
Q_E_I[2](1) (float64): [0.00089916 0.00089919 0.00089923 0.00089926 0.00089929])
Q_E_I[3](1) (float64): [-0.702038 -0.702012 -0.701986 -0.70196  -0.701934])
SensedPos_I__GPS[0](m) (float64): [-6133370. -6137350. -6141320. -6145280. -6149250.])
SensedPos_I__GPS[1](m) (float64): [-556406. -555521. -554668. -553800. -552925.])
SensedPos_I__GPS[2](m) (float64): [-3878610. -3872430. -3866250. -3860050. -3853870.])
SensedVel_I__GPS[0](m/sec) (float64): [-3984.54 -3977.82 -3971.71 -3965.34 -3959.22])
SensedVel_I__GPS[1](m/sec) (float64): [866.425 867.112 867.581 868.111 868.792])
SensedVel_I__GPS[2](m/sec) (float64): [6176.38 6180.44 6184.29 6188.55 6192.67])
AttitudeError[0](rad) (float64): [-0.927126 -0.86955  -0.80783  -0.743756 -0.677634])
AttitudeError[1](rad) (float64): [0.00187846 0.00217513 0.00173975 0.00113387 0.00151797])
AttitudeError[2](rad) (float64): [ 5.87940e-04  3.91588e-05 -2.04567e-04  3.59644e-04  6.22314e-04])
AngVel_B_I[0](rad/sec) (float64): [0.0643846 0.0671857 0.0699869 0.072003  0.071993 ])
AngVel_B_I[1](rad/sec) (float64): [-0.00024113 -0.00021601 -0.00021145 -0.00019314 -0.00015993])
AngVel_B_I[2](rad/sec) (float64): [ 5.25087e-05  2.28550e-05  1.34002e-05  1.20627e-05 -2.31949e-06])
AngVelMag_B_I(rad/sec) (float64): [0.064385  0.0671861 0.0699872 0.0720033 0.0719931])
LastNewWheelTime__RWA_A(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_B(sec) (int64): [59 60 61 62 63])
LastNewWheelTime__RWA_C(sec) (int64): [59 60 61 62 63])
SensedWheelSpeed__RWA_A(rad/sec) (float64): [-238.511 -248.887 -259.263 -266.73  -266.691])
SensedWheelSpeed__RWA_B(rad/sec) (float64): [0.603385 0.549398 0.540764 0.501152 0.427977])
SensedWheelSpeed__RWA_C(rad/sec) (float64): [-0.18033    -0.0758374  -0.0466629  -0.0480192  -0.00135342])
WheelCmd__RWA_A(N*m) (float64): [ 0.21       0.21       0.167283  -0.0032959 -0.135373 ])
WheelCmd__RWA_B(N*m) (float64): [0.00134076 0.00021221 0.00097923 0.00179637 0.0003194 ])
WheelCmd__RWA_C(N*m) (float64): [-2.37285e-03 -6.57412e-04  2.30063e-05 -1.08175e-03 -1.30528e-03])
DesiredWheelCommand[0](N*m) (float64): [-0.523805  -0.349688  -0.167283   0.0032959  0.135373 ])
DesiredWheelCommand[1](N*m) (float64): [-0.00132227 -0.0002002  -0.00097501 -0.00180123 -0.0003339 ])
DesiredWheelCommand[2](N*m) (float64): [ 0.00228494  0.00056317 -0.0001233   0.00097696  0.00119957])
WheelSpeedReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelSpeedReceived__RWA_C(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_A(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_B(1) (int64): [0 0 0 0 0])
WheelTorqueReceived__RWA_C(1) (int64): [0 0 0 0 0])
TotalTorqueRodCommand[0](A*m^2) (float64): [-0.00130954 -0.00132368 -0.00133841 -0.00135432 -0.00137196])
TotalTorqueRodCommand[1](A*m^2) (float64): [0.00011102 0.00017716 0.00024688 0.00031984 0.00039326])
TotalTorqueRodCommand[2](A*m^2) (float64): [0.0004958  0.00050185 0.00050117 0.00049321 0.00047763])
Pos_I[0](m) (float64): [-6133370. -6137350. -6141320. -6145290. -6149250.])
Pos_I[1](m) (float64): [-556397. -555532. -554661. -553797. -552929.])
Pos_I[2](m) (float64): [-3878600. -3872430. -3866250. -3860060. -3853860.])
Vel_I[0](m/sec) (float64): [-3984.08 -3977.74 -3971.38 -3965.02 -3958.64])
Vel_I[1](m/sec) (float64): [866.549 867.107 867.707 868.254 868.82 ])
Vel_I[2](m/sec) (float64): [6176.18 6180.15 6184.16 6188.16 6192.18])
ExtrapolatedPos_I[0](m) (float64): [-6133370. -6137350. -6141320. -6145280. -6149250.])
ExtrapolatedPos_I[1](m) (float64): [-556406. -555521. -554668. -553800. -552925.])
ExtrapolatedPos_I[2](m) (float64): [-3878610. -3872430. -3866250. -3860050. -3853870.])
ExtrapolatedVel_I[0](m/sec) (float64): [-3984.54 -3977.82 -3971.71 -3965.34 -3959.22])
ExtrapolatedVel_I[1](m/sec) (float64): [866.425 867.112 867.581 868.111 868.792])
ExtrapolatedVel_I[2](m/sec) (float64): [6176.38 6180.44 6184.29 6188.55 6192.67])
SemiMajorAxis(m) (float64): [7278430. 7278390. 7278380. 7278380. 7278390.])
Eccentricity(1) (float64): [4.60446e-05 3.92922e-05 3.96930e-05 4.09892e-05 4.56882e-05])
Inclination(deg) (float64): [98.038  98.0379 98.0381 98.0379 98.0378])
Raan(deg) (float64): [-179.919 -179.919 -179.919 -179.919 -179.919])
ArgPerigee(deg) (float64): [-2.96733   -0.0607155  2.85363    4.40229    6.72974  ])
TrueAnomaly(deg) (float64): [-29.5937 -32.4421 -35.2982 -36.7886 -39.0578])
Mode() (int64): [4 4 4 4 4])
TrackerValid__ST() (int64): [1 1 1 1 1])
GpsTime__GPS(sec) (int64): [1448630534 1448630535 1448630536 1448630537 1448630538])
GpsSeconds__GPS(msec) (int64): [134534 134535 134536 134537 134538])
GpsWeek__GPS() (int64): [2395 2395 2395 2395 2395])
StateOfCharge__BAT(A*hr) (int64): [521645 521679 521714 521749 521784])
PercentSoC__BAT(1) (float64): [0.803668 0.803721 0.803775 0.803829 0.803882])
DepthOfDischarge__BAT(1) (float64): [0.196332 0.196279 0.196225 0.196171 0.196118])
IncomingCharge__BAT(W) (float64): [441.417 441.417 441.418 441.419 441.419])
InEclipse() (float64): [0. 0. 0. 0. 0.])
TotalLoad__BAT(W) (float64): [23.3333 23.3333 23.3333 23.3333 23.3333])
IMUAccMag__IMU(m/sec^2) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[0](1) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[1](1) (float64): [0. 0. 0. 0. 0.])
IMUAccUnit__IMU[2](1) (float64): [0. 0. 0. 0. 0.])
IMURate_B__IMU[0](rad/sec) (float64): [0.0643846 0.0671857 0.0699869 0.072003  0.071993 ])
IMURate_B__IMU[1](rad/sec) (float64): [-0.00024113 -0.00021601 -0.00021145 -0.00019314 -0.00015993])
IMURate_B__IMU[2](rad/sec) (float64): [ 5.25087e-05  2.28550e-05  1.34002e-05  1.20627e-05 -2.31949e-06])
IMURateMag__IMU(rad/sec) (float64): [0.064385  0.0671861 0.0699872 0.0720033 0.0719931])
IMURateValid__IMU() (float64): [1. 1. 1. 1. 1.])
LastNewAccTime__IMU(sec) (float64): [0. 0. 0. 0. 0.])
LastNewTrackerTime__ST(sec) (float64): [59. 60. 61. 62. 63.])
TrackerRateMag__ST(rad/sec) (float64): [0.06388   0.0656311 0.0691753 0.0707073 0.0719267])
TrackerQ_J_ST__ST[0](1) (float64): [0.180778  0.153056  0.123868  0.0940181 0.0632673])
TrackerQ_J_ST__ST[1](1) (float64): [-0.294322 -0.311863 -0.330308 -0.348957 -0.367077])
TrackerQ_J_ST__ST[2](1) (float64): [-0.514349 -0.513975 -0.512929 -0.510908 -0.508211])
TrackerQ_J_ST__ST[3](1) (float64): [-0.784945 -0.784312 -0.782597 -0.779976 -0.776514])
BField_B__TAM[0](T) (float64): [-7.51056e-06 -7.47850e-06 -7.44639e-06 -7.41414e-06 -7.38137e-06])
BField_B__TAM[1](T) (float64): [8.47724e-06 7.07521e-06 5.58187e-06 4.00843e-06 2.39455e-06])
BField_B__TAM[2](T) (float64): [-2.17355e-05 -2.22229e-05 -2.26358e-05 -2.29584e-05 -2.31744e-05])
BField_MAG__TAM[0](T) (float64): [-7.51056e-06 -7.47850e-06 -7.44639e-06 -7.41414e-06 -7.38137e-06])
BField_MAG__TAM[1](T) (float64): [-8.47724e-06 -7.07521e-06 -5.58187e-06 -4.00843e-06 -2.39455e-06])
BField_MAG__TAM[2](T) (float64): [2.17355e-05 2.22229e-05 2.26358e-05 2.29584e-05 2.31744e-05])
LastNewMagTime__TAM(sec) (float64): [59. 60. 61. 62. 63.])
SunBetaAngle(rad) (float64): [-0.924778 -0.924779 -0.924778 -0.924779 -0.924779])
SunUnit_B[0](1) (float64): [-0.999998 -0.999998 -0.999998 -0.999999 -0.999999])
SunUnit_B[1](1) (float64): [0.00139174 0.00098096 0.00051557 0.00075551 0.00109982])
SunUnit_B[2](1) (float64): [-0.00139189 -0.00194177 -0.00167415 -0.00091881 -0.00121733])
SunSensorIsGood__MX_SN07_32() (float64): [0. 2. 2. 2. 2.])
SunSensorIsGood__MXPYPZ_SN07_29() (float64): [2. 2. 2. 2. 2.])
SunSensorIsGood__MXMYPZ_SN07_29() (float64): [2. 2. 2. 2. 2.])
SunSensorIsGood__MXMYMZ_SN07_30() (float64): [2. 2. 2. 2. 2.])
SunSensorIsGood__MXPYMZ_SN07_21() (float64): [2. 2. 2. 2. 2.])
SunSensorIsGood__PX_SN07_25() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__MXPYPZ_SN07_34() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXMYPZ_SN07_33() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXMYMZ_SN07_22() (float64): [0. 0. 0. 0. 0.])
SunSensorIsGood__PXPYMZ_SN07_28() (float64): [0. 0. 0. 0. 0.])
TrackerDataIsGood__ST() (float64): [1. 1. 1. 1. 1.])
TrackerRateIsGood__ST() (float64): [1. 1. 1. 1. 1.])
MagDataIsGood__TAM() (float64): [1. 1. 1. 1. 1.])
LastNewGpsTime__GPS(sec) (float64): [59. 60. 61. 62. 63.])
AngleToPrimaryTarget(rad) (float64): [0.00196832 0.00217549 0.00175174 0.00118954 0.00164058])
Variant (object): ['12_324.0_0' '12_324.0_0' '12_324.0_0' '12_324.0_0' '12_324.0_0'])
Run_Batch (object): ['Firesat_Attack_RWC' 'Firesat_Attack_RWC' 'Firesat_Attack_RWC'
 'Firesat_Attack_RWC' 'Firesat_Attack_RWC'])
date_loaded (object): ['2025-08-29 02:50:31.122' '2025-08-29 02:50:31.122'
 '2025-08-29 02:50:31.122' '2025-08-29 02:50:31.122'
 '2025-08-29 02:50:31.122'])
date_created (object): ['2025-08-29 02:50:30.999' '2025-08-29 02:50:30.999'
 '2025-08-29 02:50:30.999' '2025-08-29 02:50:30.999'
 '2025-08-29 02:50:30.999'])
UTC (object): ['2071-10-26 13:21:56' '2071-10-26 13:21:57' '2071-10-26 13:21:58'
 '2071-10-26 13:21:59' '2071-10-26 13:22:00'])
Longitude(deg) (float64): [-85.62625065 -85.64229347 -85.65776333 -85.67323319 -85.68870305])
Latitude(deg) (float64): [-32.34598855 -32.28857818 -32.23111051 -32.17364284 -32.11617518])
TimeDelay (float64): [324. 324. 324. 324. 324.])
AttackIntensity (float64): [0. 0. 0. 0. 0.])
Scenario (object): ['attack_rwc' 'attack_rwc' 'attack_rwc' 'attack_rwc' 'attack_rwc'])
Run_Batch_Variant (object): ['Firesat_Attack_RWC_12_324.0_0' 'Firesat_Attack_RWC_12_324.0_0'
 'Firesat_Attack_RWC_12_324.0_0' 'Firesat_Attack_RWC_12_324.0_0'
 'Firesat_Attack_RWC_12_324.0_0'])
result_label (object): ['baseline' 'baseline' 'baseline' 'baseline' 'baseline'])

In [77]:
# Add an AttackIntensity column to the metadata dataframe
# Bu şekilde metadata dataframe'ine ekstra sütunlar ekleyebiliyoruz, filtreleme ve analiz yaparken işimize yarayabilecek sütunları yani.

meta_data_df["AttackIntensity"] = meta_data_df["Variant_name"].apply(lambda x: int(x.split("_")[-1]))
meta_data_df.head()

,Variant_name,Run_Batch,Variant_path,date_created,date_loaded,FSW_rows,Simulation_columns,FSW_columns,Scenario,Month,Time_offset,Description,data_file,AttackIntensity
0,1_0.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_0....,2025-08-29T03:54:34.216196,2025-08-29T03:54:45.984822,602,69,134,baseline,January,0.0,Firesat_Baseline January Time Offset:0.0,./data/raw/baseline/fsw_data_1_0.0_0.csv,0
1,1_36.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_36...,2025-08-29T03:54:46.089648,2025-08-29T03:54:58.827963,602,69,134,baseline,January,36.0,Firesat_Baseline January Time Offset:36.0,./data/raw/baseline/fsw_data_1_36.0_0.csv,0
2,1_72.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_72...,2025-08-29T03:54:58.928442,2025-08-29T03:55:11.794282,602,69,134,baseline,January,72.0,Firesat_Baseline January Time Offset:72.0,./data/raw/baseline/fsw_data_1_72.0_0.csv,0
3,1_108.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_10...,2025-08-29T03:55:11.900084,2025-08-29T03:55:23.651383,602,69,134,baseline,January,108.0,Firesat_Baseline January Time Offset:108.0,./data/raw/baseline/fsw_data_1_108.0_0.csv,0
4,1_144.0_0,Firesat_Baseline,Firesat_Baseline/FireSat_baseline_updated_1_14...,2025-08-29T03:55:23.744846,2025-08-29T03:55:35.496401,602,69,134,baseline,January,144.0,Firesat_Baseline January Time Offset:144.0,./data/raw/baseline/fsw_data_1_144.0_0.csv,0

In [78]:
# Metadata AttackIntensity dağılımı:
meta_data_df["AttackIntensity"].value_counts()

AttackIntensity
 0     480
-50    360
-25    360
 25    360
 50    360
Name: count, dtype: int64

# Class Balance